# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable`.


class RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable < RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata
  include ::RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::AddMessageMetadata::WhenMessageIsNotAvailable::LetDefinitions
  sig { returns(T.untyped) }
  def mailer; end
end
