# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-typescript` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-typescript`.


# source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#11
module Sorbet::Typescript; end

# source://sorbet-typescript//lib/sorbet/typescript/cli.rb#11
class Sorbet::Typescript::CLI < ::Thor
  # source://sorbet-typescript//lib/sorbet/typescript/cli.rb#26
  def export; end

  private

  # source://sorbet-typescript//lib/sorbet/typescript/cli.rb#69
  sig { params(config_path: T.nilable(::String)).returns(T::Hash[::String, T.untyped]) }
  def load_configuration(config_path); end

  # source://sorbet-typescript//lib/sorbet/typescript/cli.rb#84
  sig do
    params(
      configuration: T::Hash[::String, T.untyped],
      options: T::Hash[::Symbol, T.untyped],
      key: ::String,
      option_key: ::Symbol
    ).returns(T::Array[T.any(::Module, ::String)])
  end
  def resolved_namespace_list(configuration, options, key:, option_key:); end

  # source://sorbet-typescript//lib/sorbet/typescript/cli.rb#92
  sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T::Hash[::Symbol, T.untyped]) }
  def symbolize_keys(hash); end
end

# source://sorbet-typescript//lib/sorbet/typescript/cli.rb#14
Sorbet::Typescript::CLI::DEFAULT_CONFIG = T.let(T.unsafe(nil), String)

# source://sorbet-typescript//lib/sorbet/typescript.rb#13
class Sorbet::Typescript::Error < ::StandardError; end

# source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#12
class Sorbet::Typescript::Exporter
  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#26
  sig do
    params(
      enum_namespaces: T::Array[T.any(::Module, ::String)],
      struct_namespaces: T::Array[T.any(::Module, ::String)]
    ).void
  end
  def initialize(enum_namespaces: T.unsafe(nil), struct_namespaces: T.unsafe(nil)); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#39
  sig do
    params(
      enums_json: T.nilable(::String),
      structs_json: T.nilable(::String),
      typescript_file: T.nilable(::String),
      property_map_json: T.nilable(::String)
    ).returns(::Sorbet::Typescript::Exporter::ExportData)
  end
  def export(enums_json: T.unsafe(nil), structs_json: T.unsafe(nil), typescript_file: T.unsafe(nil), property_map_json: T.unsafe(nil)); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#51
  sig { returns(::Sorbet::Typescript::Exporter::ExportData) }
  def generate_data; end

  private

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#422
  sig { params(type: ::String).returns(T::Hash[::Symbol, T.untyped]) }
  def analyse_by_string(type); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#389
  sig { params(klass: ::Module).returns(T::Hash[::Symbol, T.untyped]) }
  def analyse_class(klass); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#272
  sig { params(obj: T.untyped).returns(T::Hash[::Symbol, T.untyped]) }
  def analyse_type_object(obj); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#331
  sig { params(obj: ::T::Types::Union).returns(T::Hash[::Symbol, T.untyped]) }
  def analyse_union(obj); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#322
  sig { params(array_type: ::T::Types::TypedArray).returns(T.untyped) }
  def array_inner_type(array_type); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#491
  sig do
    params(
      info: T::Hash[::Symbol, T.untyped],
      prop_info: T::Hash[::Symbol, T.untyped]
    ).returns(T::Hash[::Symbol, T.untyped])
  end
  def augment_default_metadata(info, prop_info); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#458
  sig { params(info: T::Hash[::Symbol, T.untyped]).returns(T::Hash[::Symbol, T.untyped]) }
  def augment_enum_metadata(info); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#507
  sig { params(prop_info: T::Hash[::Symbol, T.untyped]).returns(T.untyped) }
  def default_from_prop(prop_info); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#562
  sig { params(path: ::String).void }
  def ensure_dir(path); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#548
  sig { params(enum_name: T.untyped).returns(T.nilable(T.class_of(T::Enum))) }
  def enum_class_by_name(enum_name); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#72
  sig { returns(T::Array[T.class_of(T::Enum)]) }
  def enum_classes; end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#442
  sig { params(enum_value: T.untyped).returns(T.nilable(::String)) }
  def enum_constant_name(enum_value); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#522
  sig { params(info: T::Hash[::Symbol, T.untyped]).returns(T::Array[T::Hash[::Symbol, T.untyped]]) }
  def enum_value_details_for(info); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#450
  sig { params(enum_value: T.untyped).returns(T::Hash[::Symbol, T.untyped]) }
  def enum_value_metadata(enum_value); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#97
  sig { returns(T::Hash[::String, T::Hash[::Symbol, T.untyped]]) }
  def export_enums; end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#116
  sig { returns(T::Hash[::String, T::Hash[::Symbol, T.untyped]]) }
  def export_structs; end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#262
  sig { params(prop_info: T::Hash[::Symbol, T.untyped]).returns(T::Hash[::Symbol, T.untyped]) }
  def extract_type_info(prop_info); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#88
  sig { params(name: ::String, namespaces: T::Array[::String]).returns(T::Boolean) }
  def in_namespaces?(name, namespaces); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#60
  sig { params(enum_namespaces: T::Array[T.any(::Module, ::String)]).returns(T::Array[::String]) }
  def normalize_namespaces(enum_namespaces); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#309
  sig { params(inner: ::T::Types::Base).returns(T.untyped) }
  def resolve_type(inner:); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#555
  sig { params(enum_name: T.untyped).returns(T.nilable(::String)) }
  def simple_enum_name(enum_name); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#567
  sig { params(value: T.untyped).returns(T.untyped) }
  def stringify_keys(value); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#80
  sig { returns(T::Array[T.class_of(T::Struct)]) }
  def struct_classes; end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#257
  sig { params(name: ::String).returns(::String) }
  def typescript_identifier(name); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#200
  sig do
    params(
      field_info: T::Hash[::Symbol, T.untyped],
      enums: T::Hash[::String, T::Hash[::Symbol, T.untyped]]
    ).returns(::String)
  end
  def typescript_type_for(field_info, enums); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#132
  sig { params(path: ::String, data: T::Hash[::String, T::Hash[::Symbol, T.untyped]]).void }
  def write_json(path, data); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#138
  sig { params(path: ::String, structs: T::Hash[::String, T::Hash[::Symbol, T.untyped]]).void }
  def write_property_map(path, structs); end

  # source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#153
  sig { params(path: ::String, data: ::Sorbet::Typescript::Exporter::ExportData).void }
  def write_typescript(path, data); end
end

# source://sorbet-typescript//lib/sorbet/typescript/exporter.rb#15
class Sorbet::Typescript::Exporter::ExportData < ::T::Struct
  const :enums, T::Hash[::String, T::Hash[::Symbol, T.untyped]]
  const :structs, T::Hash[::String, T::Hash[::Symbol, T.untyped]]

  class << self
    # source://sorbet-runtime/0.5.11888/lib/types/struct.rb#13
    def inherited(s); end
  end
end

# source://sorbet-typescript//lib/sorbet/typescript/version.rb#7
Sorbet::Typescript::VERSION = T.let(T.unsafe(nil), String)
