# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class ActionMailer
      class Delivered < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::Mailer, default: Source::Mailer
        const :event, Event, default: Event::Delivered
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :to, T.nilable(T::Array[String]), default: nil
        const :from, T.nilable(String), default: nil
        const :subject, T.nilable(String), default: nil

        # Event-specific fields

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::To] = to unless to.nil?
          h[LogField::From] = from unless from.nil?
          h[LogField::Subject] = subject unless subject.nil?
          h
        end
      end
    end
  end
end
