# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class ActionMailer
      class Delivery < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Mailer, default: Source::Mailer
        const :event, Event, default: Event::Delivery
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :to, T.nilable(T::Array[String]), default: nil
        const :from, T.nilable(String), default: nil
        const :subject, T.nilable(String), default: nil

        # Event-specific fields

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig {
          params(to: T.untyped,
            from: T.untyped,
            subject: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.base_hash(to: nil,
          from: nil,
          subject: nil)
          h = {}
          h[LogField::To] = to unless to.nil?
          h[LogField::From] = from unless from.nil?
          h[LogField::Subject] = subject unless subject.nil?
          h
        end

        sig {
          params(to: T.untyped,
            from: T.untyped,
            subject: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(to: nil,
          from: nil,
          subject: nil,
          additional_data: nil,
          timestamp: Time.now)
          base_hash(to: to,
            from: from,
            subject: subject)
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            to: to,
            from: from,
            subject: subject,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
