# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures`.


class RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures < RSpec::ExampleGroups::SorbetTypeSignatures
  include ::RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::SorbetTypeSignatures::LogFormatterWithSorbetTypeSignatures::LetDefinitions
  sig { returns(T.untyped) }
  def formatter; end

  sig { returns(T.untyped) }
  def test_message; end

  sig { returns(T.untyped) }
  def test_time; end
end
