require:
  - standard
  - rubocop-rspec
  - rubocop-performance
  - rubocop-sorbet

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    - tmp/**/*
    - sorbet/dsl/**/*
    - sorbet/gems/**/*
    - sorbet/annotations/**/*
  SuggestExtensions:
    rubocop-rails: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we have duplicated gems for testing

RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribedClass:
  EnforcedStyle: explicit # Much nicer for typechecking
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ScatteredLet: # We use rsig defs for each let
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false

Performance/OpenStruct:
  Exclude:
    - spec/**/*

# Sorbet RBI Rules
# ----------------------------------
Style/SingleLineMethods:
  Exclude:
    - sorbet/**/*
Style/EmptyMethod:
  Exclude:
    - sorbet/**/*
