# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures`.


class RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures < RSpec::ExampleGroups::SorbetTypes
  include ::RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::SorbetTypes::JSONFormatterWithSorbetTypeSignatures::LetDefinitions
  sig { returns(::LogStruct::JSONFormatter) }
  def formatter; end

  sig { returns(::String) }
  def test_message; end

  sig { returns(::Time) }
  def test_time; end
end
