# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures`.


class RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures < RSpec::ExampleGroups::SorbetTypes
  include ::RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::SorbetTypes::LogScrubberWithSorbetTypeSignatures::LetDefinitions
  sig { returns(::String) }
  def email; end
end
