# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "interfaces/common_fields"
require_relative "interfaces/additional_data_field"
require_relative "interfaces/request_fields"
require_relative "shared/serialize_common"
require_relative "shared/merge_additional_data_fields"
require_relative "shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class ActiveModelSerializers < T::Struct
      extend T::Sig
      include Interfaces::CommonFields
      include SerializeCommon

      const :source, Source::Rails, default: T.let(Source::Rails, Source::Rails)

      const :event, Event::Generate, default: T.let(Event::Generate, Event::Generate)
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: T.let(Level::Info, Level)

      const :message, String
      const :serializer, T.nilable(String), default: nil
      const :adapter, T.nilable(String), default: nil
      const :resource_class, T.nilable(String), default: nil
      const :duration_ms, Float

      sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
      def serialize(strict = true)
        h = serialize_common(strict)
        h[LogField::Message.serialize] = message
        h[LogField::Serializer.serialize] = serializer if serializer
        h[LogField::Adapter.serialize] = adapter if adapter
        h[LogField::ResourceClass.serialize] = resource_class if resource_class
        h[LogField::DurationMs.serialize] = duration_ms
        h
      end
    end
  end
end
