# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/source_parent.rb.erb

require_relative "active_job/enqueue"
require_relative "active_job/schedule"
require_relative "active_job/start"
require_relative "active_job/finish"

module LogStruct
  module Log
    class ActiveJob
      class BaseFields < T::Struct
        extend T::Sig
        const :job_id, String
        const :job_class, String
        const :queue_name, T.nilable(String), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil
        const :provider_job_id, T.nilable(String), default: nil

        Kwargs = T.type_alias do
          {
            job_id: String,
            job_class: String,
            queue_name: T.nilable(String),
            arguments: T.nilable(T::Array[T.untyped]),
            executions: T.nilable(Integer),
            provider_job_id: T.nilable(String)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            job_id: job_id,
            job_class: job_class,
            queue_name: queue_name,
            arguments: arguments,
            executions: executions,
            provider_job_id: provider_job_id
          }
        end
      end
    end
  end
end
