# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/source_parent.rb.erb

require_relative "action_mailer/delivery"
require_relative "action_mailer/delivered"
require_relative "action_mailer/error"

module LogStruct
  module Log
    class ActionMailer
      class BaseFields < T::Struct
        extend T::Sig
        const :to, T.nilable(T::Array[String]), default: nil
        const :from, T.nilable(String), default: nil
        const :subject, T.nilable(String), default: nil
        const :message_id, T.nilable(String), default: nil
        const :mailer_class, T.nilable(String), default: nil
        const :mailer_action, T.nilable(String), default: nil
        const :attachment_count, T.nilable(Integer), default: nil

        Kwargs = T.type_alias do
          {
            to: T.nilable(T::Array[String]),
            from: T.nilable(String),
            subject: T.nilable(String),
            message_id: T.nilable(String),
            mailer_class: T.nilable(String),
            mailer_action: T.nilable(String),
            attachment_count: T.nilable(Integer)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            to: to,
            from: from,
            subject: subject,
            message_id: message_id,
            mailer_class: mailer_class,
            mailer_action: mailer_action,
            attachment_count: attachment_count
          }
        end
      end
    end
  end
end
