# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/source_parent.rb.erb

require_relative "action_mailer/delivery"
require_relative "action_mailer/delivered"

module LogStruct
  module Log
    class ActionMailer
      class BaseFields < T::Struct
        extend T::Sig
        const :to, T.nilable(T::Array[String]), default: nil
        const :from, T.nilable(String), default: nil
        const :subject, T.nilable(String), default: nil

        Kwargs = T.type_alias do
          {
            to: T.nilable(T::Array[String]),
            from: T.nilable(String),
            subject: T.nilable(String)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            to: to,
            from: from,
            subject: subject
          }
        end
      end
    end
  end
end
