# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class ActiveModelSerializers < T::Struct
      # typed: strict
      # frozen_string_literal: true

      extend T::Sig

      extend T::Sig

      # Shared/common fields
      const :source, Source::Rails, default: Source::Rails
      const :event, Event, default: Event::Generate
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: Level::Info

      # Event-specific fields
      const :message, String
      const :serializer, T.nilable(String), default: nil
      const :adapter, T.nilable(String), default: nil
      const :resource_class, T.nilable(String), default: nil
      const :duration_ms, Float

      # Additional data

      # Request fields (optional)

      # Serialize shared fields
      include LogStruct::Log::Interfaces::CommonFields
      include LogStruct::Log::Shared::SerializeCommon

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def self.base_hash
        {}
      end

      sig {
        params(message: T.untyped,
          duration_ms: T.untyped,
          serializer: T.untyped,
          adapter: T.untyped,
          resource_class: T.untyped,
          additional_data: T.untyped,
          timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
      }
      def self.build(message:,
        duration_ms:,
        serializer: nil,
        adapter: nil,
        resource_class: nil,
        additional_data: nil,
        timestamp: Time.now)
        h = base_hash
        h[LogField::Message] = message
        h[LogField::Serializer] = serializer unless serializer.nil?
        h[LogField::Adapter] = adapter unless adapter.nil?
        h[LogField::ResourceClass] = resource_class unless resource_class.nil?
        h[LogField::DurationMs] = duration_ms
        h
      end

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def to_h
        self.class.build(
          message: message,
          serializer: serializer,
          adapter: adapter,
          resource_class: resource_class,
          duration_ms: duration_ms,
          timestamp: timestamp
        )
      end
    end
  end
end
