# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/source_parent.rb.erb

require_relative "active_storage/upload"
require_relative "active_storage/download"
require_relative "active_storage/delete"
require_relative "active_storage/metadata"
require_relative "active_storage/exist"
require_relative "active_storage/stream"
require_relative "active_storage/url"

module LogStruct
  module Log
    class ActiveStorage
      class BaseFields < T::Struct
        extend T::Sig
        const :storage, String
        const :file_id, String

        Kwargs = T.type_alias do
          {
            storage: String,
            file_id: String
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            storage: storage,
            file_id: file_id
          }
        end
      end
    end
  end
end
