# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class ActiveModelSerializers < T::Struct
      extend T::Sig

      # Shared/common fields
      const :source, Source::Rails, default: Source::Rails
      const :event, Event, default: Event::Generate
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: Level::Info

      # Event-specific fields
      const :message, String
      const :serializer, T.nilable(String), default: nil
      const :adapter, T.nilable(String), default: nil
      const :resource_class, T.nilable(String), default: nil
      const :duration_ms, Float

      # Serialize shared fields
      include LogStruct::Log::Interfaces::CommonFields
      include LogStruct::Log::Shared::SerializeCommon

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def to_h
        h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
        h[LogField::Message] = message
        h[LogField::Serializer] = serializer unless serializer.nil?
        h[LogField::Adapter] = adapter unless adapter.nil?
        h[LogField::ResourceClass] = resource_class unless resource_class.nil?
        h[LogField::DurationMs] = duration_ms
        h
      end
    end
  end
end
