# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/source_parent.rb.erb

require_relative "carrierwave/upload"
require_relative "carrierwave/delete"
require_relative "carrierwave/download"

module LogStruct
  module Log
    class CarrierWave
      class BaseFields < T::Struct
        extend T::Sig
        const :storage, String
        const :file_id, String
        const :uploader, T.nilable(String), default: nil
        const :model, T.nilable(String), default: nil
        const :mount_point, T.nilable(String), default: nil

        Kwargs = T.type_alias do
          {
            storage: String,
            file_id: String,
            uploader: T.nilable(String),
            model: T.nilable(String),
            mount_point: T.nilable(String)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            storage: storage,
            file_id: file_id,
            uploader: uploader,
            model: model,
            mount_point: mount_point
          }
        end
      end
    end
  end
end
