# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/source_parent.rb.erb

require_relative "carrierwave/upload"
require_relative "carrierwave/delete"
require_relative "carrierwave/download"

module LogStruct
  module Log
    class CarrierWave
      class BaseFields < T::Struct
        extend T::Sig
        const :storage, Symbol
        const :file_id, String
        const :uploader, T.nilable(String), default: nil
        const :model, T.nilable(String), default: nil
        const :mount_point, T.nilable(String), default: nil
        const :version, T.nilable(String), default: nil
        const :store_path, T.nilable(String), default: nil
        const :extension, T.nilable(String), default: nil

        Kwargs = T.type_alias do
          {
            storage: Symbol,
            file_id: String,
            uploader: T.nilable(String),
            model: T.nilable(String),
            mount_point: T.nilable(String),
            version: T.nilable(String),
            store_path: T.nilable(String),
            extension: T.nilable(String)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            storage: storage,
            file_id: file_id,
            uploader: uploader,
            model: model,
            mount_point: mount_point,
            version: version,
            store_path: store_path,
            extension: extension
          }
        end
      end
    end
  end
end
