# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class Error < T::Struct
      extend T::Sig

      # Shared/common fields
      const :source, Source
      const :event, Event, default: Event::Error
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: Level::Info

      # Event-specific fields
      const :err_class, T.class_of(StandardError)
      const :message, String
      const :backtrace, T.nilable(T::Array[String]), default: nil

      # Additional data
      include LogStruct::Log::Interfaces::AdditionalDataField
      const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
      include LogStruct::Log::Shared::MergeAdditionalDataFields

      # Serialize shared fields
      include LogStruct::Log::Interfaces::CommonFields
      include LogStruct::Log::Shared::SerializeCommon

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def to_h
        h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
        h[LogField::ErrClass] = err_class
        h[LogField::Message] = message
        h[LogField::Backtrace] = backtrace unless backtrace.nil?
        h
      end
    end
  end
end
