# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/source_parent.rb.erb

require_relative "good_job/log"
require_relative "good_job/enqueue"
require_relative "good_job/start"
require_relative "good_job/finish"
require_relative "good_job/error"
require_relative "good_job/schedule"

module LogStruct
  module Log
    class GoodJob
      class BaseFields < T::Struct
        extend T::Sig
        const :job_id, T.nilable(String), default: nil
        const :job_class, T.nilable(String), default: nil
        const :queue_name, T.nilable(String), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil

        Kwargs = T.type_alias do
          {
            job_id: T.nilable(String),
            job_class: T.nilable(String),
            queue_name: T.nilable(String),
            arguments: T.nilable(T::Array[T.untyped]),
            executions: T.nilable(Integer)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            job_id: job_id,
            job_class: job_class,
            queue_name: queue_name,
            arguments: arguments,
            executions: executions
          }
        end
      end
    end
  end
end
