# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/source_parent.rb.erb

require_relative "puma/boot"
require_relative "puma/started"
require_relative "puma/shutdown"
