# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "interfaces/common_fields"
require_relative "interfaces/additional_data_field"
require_relative "interfaces/request_fields"
require_relative "shared/serialize_common"
require_relative "shared/merge_additional_data_fields"
require_relative "shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class Request < T::Struct
      extend T::Sig
      include Interfaces::CommonFields
      include SerializeCommon

      include Interfaces::RequestFields
      include AddRequestFields

      const :source, Source::Rails, default: T.let(Source::Rails, Source::Rails)

      const :event, Event::Request, default: T.let(Event::Request, Event::Request)
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: T.let(Level::Info, Level)

      const :path, T.nilable(String), default: nil
      const :http_method, T.nilable(String), default: nil
      const :source_ip, T.nilable(String), default: nil
      const :user_agent, T.nilable(String), default: nil
      const :referer, T.nilable(String), default: nil
      const :request_id, T.nilable(String), default: nil
      const :format, T.nilable(String), default: nil
      const :controller, T.nilable(String), default: nil
      const :action, T.nilable(String), default: nil
      const :status, T.nilable(Integer), default: nil
      const :duration_ms, T.nilable(Float), default: nil
      const :view, T.nilable(Float), default: nil
      const :database, T.nilable(Float), default: nil
      const :params, T.nilable(T::Hash[Symbol, T.untyped]), default: nil

      sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
      def serialize(strict = true)
        h = serialize_common(strict)
        add_request_fields(h)
        h[LogField::Path.serialize] = path if path
        h[LogField::HttpMethod.serialize] = http_method if http_method
        h[LogField::SourceIp.serialize] = source_ip if source_ip
        h[LogField::UserAgent.serialize] = user_agent if user_agent
        h[LogField::Referer.serialize] = referer if referer
        h[LogField::RequestId.serialize] = request_id if request_id
        h[LogField::Format.serialize] = format if format
        h[LogField::Controller.serialize] = controller if controller
        h[LogField::Action.serialize] = action if action
        h[LogField::Status.serialize] = status if status
        h[LogField::DurationMs.serialize] = duration_ms if duration_ms
        h[LogField::View.serialize] = view if view
        h[LogField::Database.serialize] = database if database
        h[LogField::Params.serialize] = params if params
        h
      end
    end
  end
end
