# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/source_parent.rb.erb

require_relative "security/ip_spoof"
require_relative "security/csrf_violation"
require_relative "security/blocked_host"

module LogStruct
  module Log
    class Security
      class BaseFields < T::Struct
        extend T::Sig
        const :path, T.nilable(String), default: nil
        const :http_method, T.nilable(String), default: nil
        const :source_ip, T.nilable(String), default: nil
        const :user_agent, T.nilable(String), default: nil
        const :referer, T.nilable(String), default: nil
        const :request_id, T.nilable(String), default: nil

        Kwargs = T.type_alias do
          {
            path: T.nilable(String),
            http_method: T.nilable(String),
            source_ip: T.nilable(String),
            user_agent: T.nilable(String),
            referer: T.nilable(String),
            request_id: T.nilable(String)
          }
        end

        sig { returns(Kwargs) }
        def to_kwargs
          {
            path: path,
            http_method: http_method,
            source_ip: source_ip,
            user_agent: user_agent,
            referer: referer,
            request_id: request_id
          }
        end
      end
    end
  end
end
