# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/source_parent.rb.erb

require_relative "shrine/upload"
require_relative "shrine/download"
require_relative "shrine/delete"
require_relative "shrine/metadata"
require_relative "shrine/exist"
