# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/source_parent.rb.erb

require_relative "shrine/upload"
require_relative "shrine/download"
require_relative "shrine/delete"
require_relative "shrine/metadata"
require_relative "shrine/exist"
