# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class Sidekiq < T::Struct
      # typed: strict
      # frozen_string_literal: true

      extend T::Sig

      extend T::Sig

      # Shared/common fields
      const :source, Source::Sidekiq, default: Source::Sidekiq
      const :event, Event, default: Event::Log
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: Level::Info

      # Event-specific fields
      const :message, T.nilable(String), default: nil
      const :context, T.nilable(T::Hash[Symbol, T.untyped]), default: nil
      const :process_id, T.nilable(Integer), default: nil
      const :thread_id, T.nilable(T.any(Integer, String)), default: nil

      # Additional data

      # Request fields (optional)

      # Serialize shared fields
      include LogStruct::Log::Interfaces::CommonFields
      include LogStruct::Log::Shared::SerializeCommon

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def self.base_hash
        {}
      end

      sig {
        params(message: T.untyped,
          context: T.untyped,
          process_id: T.untyped,
          thread_id: T.untyped,
          additional_data: T.untyped,
          timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
      }
      def self.build(message: nil,
        context: nil,
        process_id: nil,
        thread_id: nil,
        additional_data: nil,
        timestamp: Time.now)
        h = base_hash
        h[LogField::Message] = message unless message.nil?
        h[LogField::Context] = context unless context.nil?
        h[LogField::ProcessId] = process_id unless process_id.nil?
        h[LogField::ThreadId] = thread_id unless thread_id.nil?
        h
      end

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def to_h
        self.class.build(
          message: message,
          context: context,
          process_id: process_id,
          thread_id: thread_id,
          timestamp: timestamp
        )
      end
    end
  end
end
