# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class SQL < T::Struct
      extend T::Sig

      # Shared/common fields
      const :source, Source::App, default: Source::App
      const :event, Event, default: Event::Database
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: Level::Info

      # Event-specific fields
      const :message, String
      const :sql, String
      const :name, String
      const :duration_ms, Float
      const :row_count, T.nilable(Integer), default: nil
      const :adapter, T.nilable(String), default: nil
      const :bind_params, T.nilable(T::Array[T.untyped]), default: nil
      const :database_name, T.nilable(String), default: nil
      const :connection_pool_size, T.nilable(Integer), default: nil
      const :active_connections, T.nilable(Integer), default: nil
      const :operation_type, T.nilable(String), default: nil
      const :table_names, T.nilable(T::Array[String]), default: nil

      # Additional data
      include LogStruct::Log::Interfaces::AdditionalDataField
      const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
      include LogStruct::Log::Shared::MergeAdditionalDataFields

      # Serialize shared fields
      include LogStruct::Log::Interfaces::CommonFields
      include LogStruct::Log::Shared::SerializeCommon

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def to_h
        h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
        h[LogField::Message] = message
        h[LogField::Sql] = sql
        h[LogField::Name] = name
        h[LogField::DurationMs] = duration_ms
        h[LogField::RowCount] = row_count unless row_count.nil?
        h[LogField::Adapter] = adapter unless adapter.nil?
        h[LogField::BindParams] = bind_params unless bind_params.nil?
        h[LogField::DatabaseName] = database_name unless database_name.nil?
        h[LogField::ConnectionPoolSize] = connection_pool_size unless connection_pool_size.nil?
        h[LogField::ActiveConnections] = active_connections unless active_connections.nil?
        h[LogField::OperationType] = operation_type unless operation_type.nil?
        h[LogField::TableNames] = table_names unless table_names.nil?
        h
      end
    end
  end
end
