# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class SQL < T::Struct
      # typed: strict
      # frozen_string_literal: true

      extend T::Sig

      extend T::Sig

      # Shared/common fields
      const :source, Source::App, default: Source::App
      const :event, Event, default: Event::Database
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: Level::Info

      # Event-specific fields
      const :message, String
      const :sql, String
      const :name, String
      const :duration_ms, Float
      const :row_count, T.nilable(Integer), default: nil
      const :adapter, T.nilable(String), default: nil
      const :bind_params, T.nilable(T::Array[T.untyped]), default: nil
      const :database_name, T.nilable(String), default: nil
      const :connection_pool_size, T.nilable(Integer), default: nil
      const :active_connections, T.nilable(Integer), default: nil
      const :operation_type, T.nilable(String), default: nil
      const :table_names, T.nilable(T::Array[String]), default: nil

      # Additional data
      include LogStruct::Log::Interfaces::AdditionalDataField
      const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
      include LogStruct::Log::Shared::MergeAdditionalDataFields

      # Request fields (optional)

      # Serialize shared fields
      include LogStruct::Log::Interfaces::CommonFields
      include LogStruct::Log::Shared::SerializeCommon

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def self.base_hash
        {}
      end

      sig {
        params(message: T.untyped,
          sql: T.untyped,
          name: T.untyped,
          duration_ms: T.untyped,
          row_count: T.untyped,
          adapter: T.untyped,
          bind_params: T.untyped,
          database_name: T.untyped,
          connection_pool_size: T.untyped,
          active_connections: T.untyped,
          operation_type: T.untyped,
          table_names: T.untyped,
          additional_data: T.untyped,
          timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
      }
      def self.build(message:,
        sql:,
        name:,
        duration_ms:,
        row_count: nil,
        adapter: nil,
        bind_params: nil,
        database_name: nil,
        connection_pool_size: nil,
        active_connections: nil,
        operation_type: nil,
        table_names: nil,
        additional_data: nil,
        timestamp: Time.now)
        h = base_hash
        h[LogField::Message] = message
        h[LogField::Sql] = sql
        h[LogField::Name] = name
        h[LogField::DurationMs] = duration_ms
        h[LogField::RowCount] = row_count unless row_count.nil?
        h[LogField::Adapter] = adapter unless adapter.nil?
        h[LogField::BindParams] = bind_params unless bind_params.nil?
        h[LogField::DatabaseName] = database_name unless database_name.nil?
        h[LogField::ConnectionPoolSize] = connection_pool_size unless connection_pool_size.nil?
        h[LogField::ActiveConnections] = active_connections unless active_connections.nil?
        h[LogField::OperationType] = operation_type unless operation_type.nil?
        h[LogField::TableNames] = table_names unless table_names.nil?
        h
      end

      sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
      def to_h
        self.class.build(
          message: message,
          sql: sql,
          name: name,
          duration_ms: duration_ms,
          row_count: row_count,
          adapter: adapter,
          bind_params: bind_params,
          database_name: database_name,
          connection_pool_size: connection_pool_size,
          active_connections: active_connections,
          operation_type: operation_type,
          table_names: table_names,
          additional_data: additional_data,
          timestamp: timestamp
        )
      end
    end
  end
end
