# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "interfaces/common_fields"
require_relative "interfaces/additional_data_field"
require_relative "interfaces/request_fields"
require_relative "shared/serialize_common"
require_relative "shared/merge_additional_data_fields"
require_relative "shared/add_request_fields"
require_relative "../enums/source"
require_relative "../enums/event"
require_relative "../enums/level"
require_relative "../enums/log_field"

module LogStruct
  module Log
    class SQL < T::Struct
      extend T::Sig
      include Interfaces::CommonFields
      include SerializeCommon

      include Interfaces::AdditionalDataField
      include MergeAdditionalDataFields

      const :source, Source::App, default: T.let(Source::App, Source::App)

      const :event, Event::Database, default: T.let(Event::Database, Event::Database)
      const :timestamp, Time, factory: -> { Time.now }
      const :level, Level, default: T.let(Level::Info, Level)

      const :additional_data, T::Hash[Symbol, T.untyped], default: {}
      const :message, String
      const :sql, String
      const :name, String
      const :duration_ms, Float
      const :row_count, T.nilable(Integer), default: nil
      const :adapter, T.nilable(String), default: nil
      const :bind_params, T.nilable(T::Array[T.untyped]), default: nil
      const :database_name, T.nilable(String), default: nil
      const :connection_pool_size, T.nilable(Integer), default: nil
      const :active_connections, T.nilable(Integer), default: nil
      const :operation_type, T.nilable(String), default: nil
      const :table_names, T.nilable(T::Array[String]), default: nil

      sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
      def serialize(strict = true)
        h = serialize_common(strict)
        merge_additional_data_fields(h)
        h[LogField::Message.serialize] = message
        h[LogField::Sql.serialize] = sql
        h[LogField::Name.serialize] = name
        h[LogField::DurationMs.serialize] = duration_ms
        h[LogField::RowCount.serialize] = row_count if row_count
        h[LogField::Adapter.serialize] = adapter if adapter
        h[LogField::BindParams.serialize] = bind_params if bind_params
        h[LogField::DatabaseName.serialize] = database_name if database_name
        h[LogField::ConnectionPoolSize.serialize] = connection_pool_size if connection_pool_size
        h[LogField::ActiveConnections.serialize] = active_connections if active_connections
        h[LogField::OperationType.serialize] = operation_type if operation_type
        h[LogField::TableNames.serialize] = table_names if table_names
        h
      end
    end
  end
end
