# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class GoodJob
      class Enqueue < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Job, default: Source::Job
        const :event, Event, default: Event::Enqueue
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :job_id, T.nilable(String), default: nil
        const :job_class, T.nilable(String), default: nil
        const :queue_name, T.nilable(String), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil

        # Event-specific fields
        const :duration_ms, Float
        const :scheduled_at, T.nilable(Time), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig {
          params(job_id: T.untyped,
            job_class: T.untyped,
            queue_name: T.untyped,
            arguments: T.untyped,
            executions: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.base_hash(job_id: nil,
          job_class: nil,
          queue_name: nil,
          arguments: nil,
          executions: nil)
          h = {}
          h[LogField::JobId] = job_id unless job_id.nil?
          h[LogField::JobClass] = job_class unless job_class.nil?
          h[LogField::QueueName] = queue_name unless queue_name.nil?
          h[LogField::Arguments] = arguments unless arguments.nil?
          h[LogField::Executions] = executions unless executions.nil?
          h
        end

        sig {
          params(duration_ms: T.untyped,
            job_id: T.untyped,
            job_class: T.untyped,
            queue_name: T.untyped,
            arguments: T.untyped,
            executions: T.untyped,
            scheduled_at: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(duration_ms:,
          job_id: nil,
          job_class: nil,
          queue_name: nil,
          arguments: nil,
          executions: nil,
          scheduled_at: nil,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash(job_id: job_id,
            job_class: job_class,
            queue_name: queue_name,
            arguments: arguments,
            executions: executions)
          h[LogField::DurationMs] = duration_ms
          h[LogField::ScheduledAt] = scheduled_at unless scheduled_at.nil?
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            job_id: job_id,
            job_class: job_class,
            queue_name: queue_name,
            arguments: arguments,
            executions: executions,
            duration_ms: duration_ms,
            scheduled_at: scheduled_at,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
