# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class GoodJob
      class Error < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::Job, default: Source::Job
        const :event, Event, default: Event::Error
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :job_id, T.nilable(String), default: nil
        const :job_class, T.nilable(String), default: nil
        const :queue_name, T.nilable(Symbol), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil

        # Event-specific fields
        const :error_class, String
        const :error_message, String
        const :duration_ms, T.nilable(Float), default: nil
        const :process_id, Integer
        const :thread_id, String
        const :exception_executions, T.nilable(Integer), default: nil
        const :backtrace, T.nilable(T::Array[String]), default: nil

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::JobId] = job_id unless job_id.nil?
          h[LogField::JobClass] = job_class unless job_class.nil?
          h[LogField::QueueName] = queue_name unless queue_name.nil?
          h[LogField::Arguments] = arguments unless arguments.nil?
          h[LogField::Executions] = executions unless executions.nil?
          h[LogField::ErrorClass] = error_class
          h[LogField::ErrorMessage] = error_message
          h[LogField::DurationMs] = duration_ms unless duration_ms.nil?
          h[LogField::ProcessId] = process_id
          h[LogField::ThreadId] = thread_id
          h[LogField::ExceptionExecutions] = exception_executions unless exception_executions.nil?
          h[LogField::Backtrace] = backtrace unless backtrace.nil?
          h
        end
      end
    end
  end
end
