# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class GoodJob
      class Error < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Job, default: Source::Job
        const :event, Event, default: Event::Error
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :job_id, T.nilable(String), default: nil
        const :job_class, T.nilable(String), default: nil
        const :queue_name, T.nilable(Symbol), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil

        # Event-specific fields
        const :err_class, String
        const :error_message, String
        const :duration_ms, T.nilable(Float), default: nil
        const :process_id, Integer
        const :thread_id, String
        const :exception_executions, T.nilable(Integer), default: nil
        const :backtrace, T.nilable(T::Array[String]), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig {
          params(job_id: T.untyped,
            job_class: T.untyped,
            queue_name: T.untyped,
            arguments: T.untyped,
            executions: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.base_hash(job_id: nil,
          job_class: nil,
          queue_name: nil,
          arguments: nil,
          executions: nil)
          h = {}
          h[LogField::JobId] = job_id unless job_id.nil?
          h[LogField::JobClass] = job_class unless job_class.nil?
          h[LogField::QueueName] = queue_name unless queue_name.nil?
          h[LogField::Arguments] = arguments unless arguments.nil?
          h[LogField::Executions] = executions unless executions.nil?
          h
        end

        sig {
          params(err_class: T.untyped,
            error_message: T.untyped,
            process_id: T.untyped,
            thread_id: T.untyped,
            job_id: T.untyped,
            job_class: T.untyped,
            queue_name: T.untyped,
            arguments: T.untyped,
            executions: T.untyped,
            duration_ms: T.untyped,
            exception_executions: T.untyped,
            backtrace: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(err_class:,
          error_message:,
          process_id:,
          thread_id:,
          job_id: nil,
          job_class: nil,
          queue_name: nil,
          arguments: nil,
          executions: nil,
          duration_ms: nil,
          exception_executions: nil,
          backtrace: nil,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash(job_id: job_id,
            job_class: job_class,
            queue_name: queue_name,
            arguments: arguments,
            executions: executions)
          h[LogField::ErrClass] = err_class
          h[LogField::ErrorMessage] = error_message
          h[LogField::DurationMs] = duration_ms unless duration_ms.nil?
          h[LogField::ProcessId] = process_id
          h[LogField::ThreadId] = thread_id
          h[LogField::ExceptionExecutions] = exception_executions unless exception_executions.nil?
          h[LogField::Backtrace] = backtrace unless backtrace.nil?
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            job_id: job_id,
            job_class: job_class,
            queue_name: queue_name,
            arguments: arguments,
            executions: executions,
            err_class: err_class,
            error_message: error_message,
            duration_ms: duration_ms,
            process_id: process_id,
            thread_id: thread_id,
            exception_executions: exception_executions,
            backtrace: backtrace,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
