# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "../interfaces/common_fields"
require_relative "../interfaces/additional_data_field"
require_relative "../interfaces/request_fields"
require_relative "../shared/serialize_common"
require_relative "../shared/merge_additional_data_fields"
require_relative "../shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class GoodJob
      class Error < T::Struct
        extend T::Sig
        include Interfaces::CommonFields
        include SerializeCommon

        include Interfaces::AdditionalDataField
        include MergeAdditionalDataFields

        const :source, Source::Job, default: T.let(Source::Job, Source::Job)

        const :event, Event::Error, default: T.let(Event::Error, Event::Error)
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: T.let(Level::Info, Level)

        const :job_id, T.nilable(String), default: nil
        const :job_class, T.nilable(String), default: nil
        const :queue_name, T.nilable(String), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil
        const :additional_data, T::Hash[Symbol, T.untyped], default: {}
        const :err_class, String
        const :error_message, String
        const :duration_ms, T.nilable(Float), default: nil
        const :process_id, Integer
        const :thread_id, String
        const :exception_executions, T.nilable(Integer), default: nil
        const :backtrace, T.nilable(T::Array[String]), default: nil

        sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
        def serialize(strict = true)
          h = serialize_common(strict)
          h[LogField::JobId.serialize] = job_id if job_id
          h[LogField::JobClass.serialize] = job_class if job_class
          h[LogField::QueueName.serialize] = queue_name if queue_name
          h[LogField::Arguments.serialize] = arguments if arguments
          h[LogField::Executions.serialize] = executions if executions
          merge_additional_data_fields(h)
          h[LogField::ErrClass.serialize] = err_class
          h[LogField::ErrorMessage.serialize] = error_message
          h[LogField::DurationMs.serialize] = duration_ms if duration_ms
          h[LogField::ProcessId.serialize] = process_id
          h[LogField::ThreadId.serialize] = thread_id
          h[LogField::ExceptionExecutions.serialize] = exception_executions if exception_executions
          h[LogField::Backtrace.serialize] = backtrace if backtrace
          h
        end
      end
    end
  end
end
