# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "../interfaces/common_fields"
require_relative "../interfaces/additional_data_field"
require_relative "../interfaces/request_fields"
require_relative "../shared/serialize_common"
require_relative "../shared/merge_additional_data_fields"
require_relative "../shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class GoodJob
      class Finish < T::Struct
        extend T::Sig
        include Interfaces::CommonFields
        include SerializeCommon

        include Interfaces::AdditionalDataField
        include MergeAdditionalDataFields

        const :source, Source::Job, default: T.let(Source::Job, Source::Job)

        const :event, Event::Finish, default: T.let(Event::Finish, Event::Finish)
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: T.let(Level::Info, Level)

        const :job_id, T.nilable(String), default: nil
        const :job_class, T.nilable(String), default: nil
        const :queue_name, T.nilable(String), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil
        const :additional_data, T::Hash[Symbol, T.untyped], default: {}
        const :duration_ms, Float
        const :finished_at, Time
        const :process_id, Integer
        const :thread_id, String

        sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
        def serialize(strict = true)
          h = serialize_common(strict)
          h[LogField::JobId.serialize] = job_id if job_id
          h[LogField::JobClass.serialize] = job_class if job_class
          h[LogField::QueueName.serialize] = queue_name if queue_name
          h[LogField::Arguments.serialize] = arguments if arguments
          h[LogField::Executions.serialize] = executions if executions
          merge_additional_data_fields(h)
          h[LogField::DurationMs.serialize] = duration_ms
          h[LogField::FinishedAt.serialize] = finished_at.iso8601
          h[LogField::ProcessId.serialize] = process_id
          h[LogField::ThreadId.serialize] = thread_id
          h
        end
      end
    end
  end
end
