module RailsStructuredLogging
  # Based on https://github.com/ankane/logstop
  # Module for scrubbing sensitive information from log messages
  module LogstopFork
    class << self
      attr_accessor email_salt: String

      # Scrub sensitive information from a string
      # @param msg [String] The message to scrub
      # @param scrubber [Proc] A custom scrubber to apply
      # @return [String] The scrubbed message
      def scrub: (untyped msg, ?scrubber: Proc?) -> String

      # Get or set the email salt used for hashing emails
      # @return [String] The email salt
      def email_salt: () -> String
    end
  end
end 
