# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Security
      class BlockedHost < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Security, default: Source::Security
        const :event, Event, default: Event::BlockedHost
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :path, T.nilable(String), default: nil
        const :http_method, T.nilable(String), default: nil
        const :source_ip, T.nilable(String), default: nil
        const :user_agent, T.nilable(String), default: nil
        const :referer, T.nilable(String), default: nil
        const :request_id, T.nilable(String), default: nil

        # Event-specific fields
        const :message, T.nilable(String), default: nil
        const :blocked_host, T.nilable(String), default: nil
        const :blocked_hosts, T.nilable(T::Array[String]), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)
        include LogStruct::Log::Interfaces::RequestFields

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon
        include LogStruct::Log::Shared::AddRequestFields

        sig {
          params(path: T.untyped,
            http_method: T.untyped,
            source_ip: T.untyped,
            user_agent: T.untyped,
            referer: T.untyped,
            request_id: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.base_hash(path: nil,
          http_method: nil,
          source_ip: nil,
          user_agent: nil,
          referer: nil,
          request_id: nil)
          h = {}
          h[LogField::Path] = path unless path.nil?
          h[LogField::HttpMethod] = http_method unless http_method.nil?
          h[LogField::SourceIp] = source_ip unless source_ip.nil?
          h[LogField::UserAgent] = user_agent unless user_agent.nil?
          h[LogField::Referer] = referer unless referer.nil?
          h[LogField::RequestId] = request_id unless request_id.nil?
          h
        end

        sig {
          params(path: T.untyped,
            http_method: T.untyped,
            source_ip: T.untyped,
            user_agent: T.untyped,
            referer: T.untyped,
            request_id: T.untyped,
            message: T.untyped,
            blocked_host: T.untyped,
            blocked_hosts: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(path: nil,
          http_method: nil,
          source_ip: nil,
          user_agent: nil,
          referer: nil,
          request_id: nil,
          message: nil,
          blocked_host: nil,
          blocked_hosts: nil,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash(path: path,
            http_method: http_method,
            source_ip: source_ip,
            user_agent: user_agent,
            referer: referer,
            request_id: request_id)
          h[LogField::Message] = message unless message.nil?
          h[LogField::BlockedHost] = blocked_host unless blocked_host.nil?
          h[LogField::BlockedHosts] = blocked_hosts unless blocked_hosts.nil?
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            path: path,
            http_method: http_method,
            source_ip: source_ip,
            user_agent: user_agent,
            referer: referer,
            request_id: request_id,
            message: message,
            blocked_host: blocked_host,
            blocked_hosts: blocked_hosts,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
