# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Security
      class IPSpoof < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::Security, default: Source::Security
        const :event, Event, default: Event::IPSpoof
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :path, T.nilable(String), default: nil
        const :http_method, T.nilable(String), default: nil
        const :source_ip, T.nilable(String), default: nil
        const :user_agent, T.nilable(String), default: nil
        const :referer, T.nilable(String), default: nil
        const :request_id, T.nilable(String), default: nil

        # Event-specific fields
        const :message, T.nilable(String), default: nil
        const :client_ip, T.nilable(String), default: nil
        const :x_forwarded_for, T.nilable(String), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)
        include LogStruct::Log::Interfaces::RequestFields

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon
        include LogStruct::Log::Shared::AddRequestFields

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::Path] = path unless path.nil?
          h[LogField::HttpMethod] = http_method unless http_method.nil?
          h[LogField::SourceIp] = source_ip unless source_ip.nil?
          h[LogField::UserAgent] = user_agent unless user_agent.nil?
          h[LogField::Referer] = referer unless referer.nil?
          h[LogField::RequestId] = request_id unless request_id.nil?
          h[LogField::Message] = message unless message.nil?
          h[LogField::ClientIp] = client_ip unless client_ip.nil?
          h[LogField::XForwardedFor] = x_forwarded_for unless x_forwarded_for.nil?
          h
        end
      end
    end
  end
end
