# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection`.


class RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection < RSpec::Core::ExampleGroup
  include ::RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::LogStructIntegrationsActionMailerMetadataCollection::LetDefinitions
  sig { returns(T.untyped) }
  def mailer; end

  sig { returns(T.untyped) }
  def message; end
end
