# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::LogStructLogFormatter`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::LogStructLogFormatter`.


class RSpec::ExampleGroups::LogStructLogFormatter < RSpec::Core::ExampleGroup
  include ::RSpec::ExampleGroups::LogStructLogFormatter::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig { params(block: T.proc.bind(RSpec::ExampleGroups::LogStructLogFormatter).void).returns(T.untyped) }
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::LogStructLogFormatter::LetDefinitions
  sig { returns(T.untyped) }
  def iso_time; end

  sig { returns(T.untyped) }
  def progname; end

  sig { returns(T.untyped) }
  def severity; end

  sig { returns(T.untyped) }
  def time; end
end
