# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter`.


class RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter < RSpec::Core::ExampleGroup
  include ::RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::RailsStructuredLoggingMultiErrorReporter::LetDefinitions
  sig { returns(T.untyped) }
  def context; end

  sig { returns(T.untyped) }
  def exception; end

  sig { returns(T.untyped) }
  def reporter; end
end
