# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::SorbetTypes`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::SorbetTypes`.


class RSpec::ExampleGroups::SorbetTypes < RSpec::Core::ExampleGroup
  include ::RSpec::ExampleGroups::SorbetTypes::LetDefinitions

  class << self
    sig { params(args: T.untyped, block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def after(*args, &block); end

    sig { params(args: T.untyped, block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def before(*args, &block); end

    sig { params(all_args: T.untyped, block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def it(*all_args, &block); end

    sig { params(name: T.untyped, block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def let(*name, &block); end

    sig { params(name: T.untyped, block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def let!(*name, &block); end

    sig { params(all_args: T.untyped, block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def specify(*all_args, &block); end

    sig { params(block: T.proc.bind(RSpec::ExampleGroups::SorbetTypes).void).returns(T.untyped) }
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::SorbetTypes::LetDefinitions
  sig { returns(T::Boolean) }
  def enabled; end

  sig { returns(T::Boolean) }
  def filter_credit_cards; end

  sig { returns(T::Boolean) }
  def filter_emails; end

  sig { returns(T::Boolean) }
  def lograge_enabled; end

  sig { returns(::String) }
  def logstop_email_salt; end
end
