# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::SorbetTypeSignatures`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::SorbetTypeSignatures`.


class RSpec::ExampleGroups::SorbetTypeSignatures < RSpec::Core::ExampleGroup
  include ::RSpec::ExampleGroups::SorbetTypeSignatures::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig { params(block: T.proc.bind(RSpec::ExampleGroups::SorbetTypeSignatures).void).returns(T.untyped) }
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::SorbetTypeSignatures::LetDefinitions
  sig { returns(T::Boolean) }
  def enabled; end

  sig { returns(T.untyped) }
  def filter_credit_cards; end

  sig { returns(T.untyped) }
  def filter_emails; end

  sig { returns(T.untyped) }
  def lograge_enabled; end

  sig { returns(T.untyped) }
  def logstop_email_salt; end
end
