# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks`.


class RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks < RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks
  include ::RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::LogStructIntegrationsActionMailerCallbacks::DeliveryCallbacks::LetDefinitions
  sig { returns(T.untyped) }
  def test_mailer; end

  sig { returns(T.untyped) }
  def test_mailer_class; end
end
