# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs`.


class RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs < RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call
  include ::RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::RailsStructuredLoggingLogFormatter::Call::WithActiveJobLogs::LetDefinitions
  sig { returns(T.untyped) }
  def user; end

  sig { returns(T.untyped) }
  def user_class; end
end
