# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined`.
# Please instead update this file by running `bin/tapioca dsl RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined`.


class RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined < RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData
  include ::RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined::LetDefinitions

  class << self
    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def after(*args, &block); end

    sig do
      params(
        args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def before(*args, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def it(*all_args, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def let(*name, &block); end

    sig do
      params(
        name: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def let!(*name, &block); end

    sig do
      params(
        all_args: T.untyped,
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def specify(*all_args, &block); end

    sig do
      params(
        block: T.proc.bind(RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined).void
      ).returns(T.untyped)
    end
    def subject(&block); end
  end
end

module RSpec::ExampleGroups::RailsStructuredLoggingIntegrationsActionMailerMetadataCollection::ExtractIdsToLogData::WhenInstanceVariablesAreDefined::LetDefinitions
  sig { returns(T.untyped) }
  def account; end

  sig { returns(T.untyped) }
  def user; end
end
