import { LogGenerator } from "../generator";
import { SampleData } from "../sample-data";

describe("LogGenerator", () => {
  let generator: LogGenerator;

  beforeEach(() => {
    // Use a fixed seed for deterministic tests
    generator = new LogGenerator(12345);
  });

  test("should generate consistent random values with the same seed", () => {
    const generator1 = new LogGenerator(42);
    const generator2 = new LogGenerator(42);

    expect(generator1.randomInt(1, 100)).toBe(generator2.randomInt(1, 100));
    expect(generator1.randomFloat(1, 100)).toBe(generator2.randomFloat(1, 100));
    expect(generator1.randomHex(8)).toBe(generator2.randomHex(8));
  });

  test("should generate different values with different seeds", () => {
    const generator1 = new LogGenerator(42);
    const generator2 = new LogGenerator(43);

    // There's a very small chance these could be equal by coincidence,
    // but it's extremely unlikely
    expect(generator1.randomInt(1, 100000)).not.toBe(
      generator2.randomInt(1, 100000)
    );
  });

  test("should generate random email addresses", () => {
    const email = generator.randomEmail();

    expect(email).toContain("@");
    expect(email.split("@").length).toBe(2);

    // Should include a name from our sample data
    const firstNames = SampleData.FIRST_NAMES.map((name) => name.toLowerCase());
    const lastNames = SampleData.LAST_NAMES.map((name) => name.toLowerCase());

    const namePart = email.split("@")[0];
    const domain = email.split("@")[1];

    // Check first part is firstName.lastName format
    const nameParts = namePart.split(".");
    expect(nameParts.length).toBe(2);
    expect(firstNames).toContain(nameParts[0]);
    expect(lastNames).toContain(nameParts[1]);

    // Check domain is from our list
    expect(SampleData.DOMAINS).toContain(domain);
  });

  test("should generate filtered email addresses", () => {
    const filteredEmail = generator.randomEmail(true);

    expect(filteredEmail).toMatch(/^\[EMAIL:[a-f0-9]{6}\]$/);
  });

  test("should generate filtered email address objects", () => {
    const filteredEmailObj = generator.randomEmail(true, true) as any;

    expect(filteredEmailObj).toHaveProperty("_filtered");
    expect(filteredEmailObj._filtered).toHaveProperty("_class", "String");
    expect(filteredEmailObj._filtered).toHaveProperty("_bytes");
    expect(filteredEmailObj._filtered).toHaveProperty("_hash");
    expect(filteredEmailObj._filtered._hash).toMatch(/^[a-f0-9]{6}$/);
  });

  test("should generate filtered hash objects", () => {
    const filteredHash = generator.filteredHash("password") as any;

    expect(filteredHash).toHaveProperty("_filtered");
    expect(filteredHash._filtered).toHaveProperty("_class", "Hash");
    expect(filteredHash._filtered).toHaveProperty("_keys_count");
    expect(filteredHash._filtered).toHaveProperty("_keys");
    expect(filteredHash._filtered).toHaveProperty("_bytes");

    // Check that keys include password-related fields
    expect(filteredHash._filtered._keys).toContain("password");
  });

  test("should generate filtered array objects", () => {
    const filteredArray = generator.filteredArray(5) as any;

    expect(filteredArray).toHaveProperty("_filtered");
    expect(filteredArray._filtered).toHaveProperty("_class", "Array");
    expect(filteredArray._filtered).toHaveProperty("_length", 5);
    expect(filteredArray._filtered).toHaveProperty("_bytes");
  });

  test("should generate filtered sensitive values", () => {
    expect(generator.randomPassword()).toBe("[PASSWORD]");
    expect(generator.randomCreditCard()).toBe("[CREDIT_CARD]");
    expect(generator.randomPhone()).toBe("[PHONE]");
    expect(generator.randomIP(true)).toBe("[IP]");
  });

  test("should generate unfiltered sensitive values when requested", () => {
    expect(generator.randomPassword(false)).toContain("password");
    expect(generator.randomCreditCard(false)).toMatch(
      /^\d{4}-\d{4}-\d{4}-\d{4}$/
    );
    expect(generator.randomPhone(false)).toMatch(/^\+1-\d{3}-\d{3}-\d{4}$/);
    expect(SampleData.IP_ADDRESSES).toContain(generator.randomIP(false));
  });

  // We'll skip testing the generateLog method since it depends on the actual
  // log_types.json file which is generated by the Ruby exporter
  // In a real implementation, we would use a fixture instead

  test("should generate job sequences", () => {
    const sequence = generator.generateJobSequence();

    // Should have 3 logs: enqueue, start, finish
    expect(sequence).toHaveLength(3);

    // All should have the same job_id
    const jobId = sequence[0].job_id;
    expect(sequence[1].job_id).toBe(jobId);
    expect(sequence[2].job_id).toBe(jobId);

    // Should have the right event types
    expect(sequence[0].event).toBe("enqueue");
    expect(sequence[1].event).toBe("start");
    expect(sequence[2].event).toBe("finish");

    // Only the finish event should have a duration
    expect(sequence[0]).not.toHaveProperty("duration");
    expect(sequence[1]).not.toHaveProperty("duration");
    expect(sequence[2]).toHaveProperty("duration");

    // Timestamps should be in chronological order
    const time1 = new Date(sequence[0].timestamp).getTime();
    const time2 = new Date(sequence[1].timestamp).getTime();
    const time3 = new Date(sequence[2].timestamp).getTime();

    expect(time1).toBeLessThan(time2);
    expect(time2).toBeLessThan(time3);
  });
});
