import { LogGenerator } from "../log-generator";

describe("LogGenerator", () => {
  let generator: LogGenerator;

  beforeEach(() => {
    // Use a fixed seed for deterministic tests
    generator = new LogGenerator(12345);
  });

  // We'll skip testing the generateLog method since it depends on the actual
  // log_types.json file which is generated by the Ruby exporter
  // In a real implementation, we would use a fixture instead

  test("should generate job sequences", () => {
    const sequence = generator.generateJobSequence();

    // Should have 3 logs: enqueue, start, finish
    expect(sequence).toHaveLength(3);

    // All should have the same job_id
    const jobId = sequence[0].job_id;
    expect(sequence[1].job_id).toBe(jobId);
    expect(sequence[2].job_id).toBe(jobId);

    // Should have the right event types
    expect(sequence[0].event).toBe("enqueue");
    expect(sequence[1].event).toBe("start");
    expect(sequence[2].event).toBe("finish");

    // Only the finish event should have a duration
    expect(sequence[0]).not.toHaveProperty("duration");
    expect(sequence[1]).not.toHaveProperty("duration");
    expect(sequence[2]).toHaveProperty("duration");

    // Timestamps should be in chronological order
    const time1 = new Date(sequence[0].timestamp).getTime();
    const time2 = new Date(sequence[1].timestamp).getTime();
    const time3 = new Date(sequence[2].timestamp).getTime();

    expect(time1).toBeLessThan(time2);
    expect(time2).toBeLessThan(time3);
  });
});