# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class CarrierWave
      class Delete < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::CarrierWave, default: Source::CarrierWave
        const :event, Event, default: Event::Delete
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :storage, Symbol
        const :file_id, String
        const :uploader, T.nilable(String), default: nil
        const :model, T.nilable(String), default: nil
        const :mount_point, T.nilable(String), default: nil

        # Event-specific fields

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig {
          params(storage: T.untyped,
            file_id: T.untyped,
            uploader: T.untyped,
            model: T.untyped,
            mount_point: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.base_hash(storage: nil,
          file_id: nil,
          uploader: nil,
          model: nil,
          mount_point: nil)
          h = {}
          h[LogField::Storage] = storage unless storage.nil?
          h[LogField::FileId] = file_id unless file_id.nil?
          h[LogField::Uploader] = uploader unless uploader.nil?
          h[LogField::Model] = model unless model.nil?
          h[LogField::MountPoint] = mount_point unless mount_point.nil?
          h
        end

        sig {
          params(storage: T.untyped,
            file_id: T.untyped,
            uploader: T.untyped,
            model: T.untyped,
            mount_point: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(storage:,
          file_id:,
          uploader: nil,
          model: nil,
          mount_point: nil,
          additional_data: nil,
          timestamp: Time.now)
          base_hash(storage: storage,
            file_id: file_id,
            uploader: uploader,
            model: model,
            mount_point: mount_point)
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            storage: storage,
            file_id: file_id,
            uploader: uploader,
            model: model,
            mount_point: mount_point,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
