# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "../interfaces/common_fields"
require_relative "../interfaces/additional_data_field"
require_relative "../interfaces/request_fields"
require_relative "../shared/serialize_common"
require_relative "../shared/merge_additional_data_fields"
require_relative "../shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class CarrierWave
      class Delete < T::Struct
        extend T::Sig
        include Interfaces::CommonFields
        include SerializeCommon

        include Interfaces::AdditionalDataField
        include MergeAdditionalDataFields

        const :source, Source::CarrierWave, default: T.let(Source::CarrierWave, Source::CarrierWave)

        const :event, Event::Delete, default: T.let(Event::Delete, Event::Delete)
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: T.let(Level::Info, Level)

        const :storage, String
        const :file_id, String
        const :uploader, T.nilable(String), default: nil
        const :model, T.nilable(String), default: nil
        const :mount_point, T.nilable(String), default: nil
        const :additional_data, T::Hash[Symbol, T.untyped], default: {}

        sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
        def serialize(strict = true)
          h = serialize_common(strict)
          h[LogField::Storage.serialize] = storage if storage
          h[LogField::FileId.serialize] = file_id if file_id
          h[LogField::Uploader.serialize] = uploader if uploader
          h[LogField::Model.serialize] = model if model
          h[LogField::MountPoint.serialize] = mount_point if mount_point
          merge_additional_data_fields(h)
          h
        end
      end
    end
  end
end
