# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class CarrierWave
      class Delete < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::CarrierWave, default: Source::CarrierWave
        const :event, Event, default: Event::Delete
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :storage, Symbol
        const :file_id, String
        const :uploader, T.nilable(String), default: nil
        const :model, T.nilable(String), default: nil
        const :mount_point, T.nilable(String), default: nil
        const :version, T.nilable(String), default: nil
        const :store_path, T.nilable(String), default: nil
        const :extension, T.nilable(String), default: nil

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::Storage] = storage
          h[LogField::FileId] = file_id
          h[LogField::Uploader] = uploader unless uploader.nil?
          h[LogField::Model] = model unless model.nil?
          h[LogField::MountPoint] = mount_point unless mount_point.nil?
          h[LogField::Version] = version unless version.nil?
          h[LogField::StorePath] = store_path unless store_path.nil?
          h[LogField::Extension] = extension unless extension.nil?
          h
        end
      end
    end
  end
end
