# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Dotenv
      class Save < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Dotenv, default: Source::Dotenv
        const :event, Event, default: Event::Save
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        # Event-specific fields
        const :snapshot, T::Boolean

        # Additional data

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def self.base_hash
          {}
        end

        sig {
          params(snapshot: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(snapshot:,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash
          h[LogField::Snapshot] = snapshot
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            snapshot: snapshot,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
