module RailsStructuredLogging
  VERSION: String

  class Error < StandardError
  end

  # Configuration class for RailsStructuredLogging
  class Configuration
    attr_accessor enabled: bool?
    attr_accessor lograge_enabled: bool
    attr_accessor logstop_email_salt: String
    attr_accessor lograge_custom_options: ^(untyped, untyped) -> untyped
    attr_accessor actionmailer_integration_enabled: bool
    attr_accessor host_authorization_enabled: bool
    attr_accessor activejob_integration_enabled: bool
    attr_accessor rack_middleware_enabled: bool
    attr_accessor sidekiq_integration_enabled: bool
    attr_accessor shrine_integration_enabled: bool
    attr_accessor filter_emails: bool
    attr_accessor filter_url_passwords: bool
    attr_accessor filter_credit_cards: bool
    attr_accessor filter_phones: bool
    attr_accessor filter_ssns: bool
    attr_accessor filter_ips: bool
    attr_accessor filter_macs: bool

    def initialize: () -> void
  end

  # Class methods for RailsStructuredLogging module
  class << self
    attr_accessor configuration: Configuration

    # Configure the gem with a block
    def configure: () ?{ (Configuration) -> void } -> void

    # Set up the integrations
    def setup_integrations: () -> void

    # Check if the gem is enabled
    def enabled?: () -> bool
  end
end 
