# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RailsStructuredLogging::Integrations::ActionMailer::Callbacks`.
# Please instead update this file by running `bin/tapioca dsl RailsStructuredLogging::Integrations::ActionMailer::Callbacks`.


module RailsStructuredLogging::Integrations::ActionMailer::Callbacks
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def __callbacks; end
    def __callbacks=(value); end
    def __callbacks?; end
  end

  module GeneratedInstanceMethods
    def __callbacks; end
    def __callbacks?; end
  end
end
