# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class ActiveStorage
      class Delete < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::Storage, default: Source::Storage
        const :event, Event, default: Event::Delete
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :storage, Symbol
        const :file_id, String

        # Event-specific fields

        # Additional data

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::Storage] = storage
          h[LogField::FileId] = file_id
          h
        end
      end
    end
  end
end
