# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "../interfaces/common_fields"
require_relative "../interfaces/additional_data_field"
require_relative "../interfaces/request_fields"
require_relative "../shared/serialize_common"
require_relative "../shared/merge_additional_data_fields"
require_relative "../shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class ActiveStorage
      class Exist < T::Struct
        extend T::Sig
        include Interfaces::CommonFields
        include SerializeCommon

        const :source, Source::Storage, default: T.let(Source::Storage, Source::Storage)

        const :event, Event::Exist, default: T.let(Event::Exist, Event::Exist)
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: T.let(Level::Info, Level)

        const :storage, String
        const :file_id, String
        const :exist, T.nilable(T::Boolean), default: nil

        sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
        def serialize(strict = true)
          h = serialize_common(strict)
          h[LogField::Storage.serialize] = storage if storage
          h[LogField::FileId.serialize] = file_id if file_id
          h[LogField::Exist.serialize] = exist if exist
          h
        end
      end
    end
  end
end
