# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class ActiveStorage
      class Url < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Storage, default: Source::Storage
        const :event, Event, default: Event::Url
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :storage, Symbol
        const :file_id, String

        # Event-specific fields
        const :url, String

        # Additional data

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig {
          params(storage: T.untyped,
            file_id: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.base_hash(storage: nil,
          file_id: nil)
          h = {}
          h[LogField::Storage] = storage unless storage.nil?
          h[LogField::FileId] = file_id unless file_id.nil?
          h
        end

        sig {
          params(url: T.untyped,
            storage: T.untyped,
            file_id: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(url:,
          storage:,
          file_id:,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash(storage: storage,
            file_id: file_id)
          h[LogField::Url] = url
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            storage: storage,
            file_id: file_id,
            url: url,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
