# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Puma
      class Shutdown < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Puma, default: Source::Puma
        const :event, Event, default: Event::Shutdown
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        # Event-specific fields
        const :process_id, T.nilable(Integer), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def self.base_hash
          {}
        end

        sig {
          params(process_id: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(process_id: nil,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash
          h[LogField::ProcessId] = process_id unless process_id.nil?
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            process_id: process_id,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
