# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_sorbet_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "../interfaces/common_fields"
require_relative "../interfaces/additional_data_field"
require_relative "../interfaces/request_fields"
require_relative "../shared/serialize_common"
require_relative "../shared/merge_additional_data_fields"
require_relative "../shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Puma
      class Shutdown < T::Struct
        extend T::Sig
        include Interfaces::CommonFields
        include SerializeCommon

        include Interfaces::AdditionalDataField
        include MergeAdditionalDataFields

        const :source, Source::Puma, default: T.let(Source::Puma, Source::Puma)

        const :event, Event::Shutdown, default: T.let(Event::Shutdown, Event::Shutdown)
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: T.let(Level::Info, Level)

        const :additional_data, T::Hash[Symbol, T.untyped], default: {}
        const :process_id, T.nilable(Integer), default: nil

        sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
        def serialize(strict = true)
          h = serialize_common(strict)
          merge_additional_data_fields(h)
          h[LogField::ProcessId.serialize] = process_id if process_id
          h
        end
      end
    end
  end
end
