# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Puma
      class Start < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::Puma, default: Source::Puma
        const :event, Event, default: Event::Start
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        # Event-specific fields
        const :mode, T.nilable(String), default: nil
        const :puma_version, T.nilable(String), default: nil
        const :puma_codename, T.nilable(String), default: nil
        const :ruby_version, T.nilable(String), default: nil
        const :min_threads, T.nilable(Integer), default: nil
        const :max_threads, T.nilable(Integer), default: nil
        const :environment, T.nilable(String), default: nil
        const :process_id, T.nilable(Integer), default: nil
        const :listening_addresses, T.nilable(T::Array[String]), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::Mode] = mode unless mode.nil?
          h[LogField::PumaVersion] = puma_version unless puma_version.nil?
          h[LogField::PumaCodename] = puma_codename unless puma_codename.nil?
          h[LogField::RubyVersion] = ruby_version unless ruby_version.nil?
          h[LogField::MinThreads] = min_threads unless min_threads.nil?
          h[LogField::MaxThreads] = max_threads unless max_threads.nil?
          h[LogField::Environment] = environment unless environment.nil?
          h[LogField::ProcessId] = process_id unless process_id.nil?
          h[LogField::ListeningAddresses] = listening_addresses unless listening_addresses.nil?
          h
        end
      end
    end
  end
end
