# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Puma
      class Started < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Puma, default: Source::Puma
        const :event, Event, default: Event::Started
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        # Event-specific fields
        const :mode, T.nilable(String), default: nil
        const :puma_version, T.nilable(String), default: nil
        const :puma_codename, T.nilable(String), default: nil
        const :ruby_version, T.nilable(String), default: nil
        const :min_threads, T.nilable(Integer), default: nil
        const :max_threads, T.nilable(Integer), default: nil
        const :environment, T.nilable(String), default: nil
        const :process_id, T.nilable(Integer), default: nil
        const :listening_addresses, T.nilable(T::Array[String]), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def self.base_hash
          {}
        end

        sig {
          params(mode: T.untyped,
            puma_version: T.untyped,
            puma_codename: T.untyped,
            ruby_version: T.untyped,
            min_threads: T.untyped,
            max_threads: T.untyped,
            environment: T.untyped,
            process_id: T.untyped,
            listening_addresses: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(mode: nil,
          puma_version: nil,
          puma_codename: nil,
          ruby_version: nil,
          min_threads: nil,
          max_threads: nil,
          environment: nil,
          process_id: nil,
          listening_addresses: nil,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash
          h[LogField::Mode] = mode unless mode.nil?
          h[LogField::PumaVersion] = puma_version unless puma_version.nil?
          h[LogField::PumaCodename] = puma_codename unless puma_codename.nil?
          h[LogField::RubyVersion] = ruby_version unless ruby_version.nil?
          h[LogField::MinThreads] = min_threads unless min_threads.nil?
          h[LogField::MaxThreads] = max_threads unless max_threads.nil?
          h[LogField::Environment] = environment unless environment.nil?
          h[LogField::ProcessId] = process_id unless process_id.nil?
          h[LogField::ListeningAddresses] = listening_addresses unless listening_addresses.nil?
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            mode: mode,
            puma_version: puma_version,
            puma_codename: puma_codename,
            ruby_version: ruby_version,
            min_threads: min_threads,
            max_threads: max_threads,
            environment: environment,
            process_id: process_id,
            listening_addresses: listening_addresses,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
