# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module LogStruct::Integrations::ActionMailer::ErrorHandling::LogTypes; end
module LogStruct::LogEvent::CarrierWave; end
module LogStruct::LogEvent::Shrine; end
module LogStruct::LogTypes; end
