# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Shrine; end
module ::Sidekiq; end
module ::Sidekiq::Context; end
module ::Sidekiq::Logger::Formatters::Base; end
module ActiveModel::Error; end
module ActiveRecord::ConnectionAdapters::DatabaseStatements; end
module ActiveRecord::ConnectionAdapters::SchemaStatements; end
module RailsStructuredLogging::ActiveJob::Logging; end
