#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require "json"
require "fileutils"

root = File.expand_path("..", __dir__)
docs_generated = File.join(root, "docs", "generated", "logstruct")
structs_path = File.join(docs_generated, "sorbet-log-structs.json")
enums_path = File.join(docs_generated, "sorbet-enums.json")

unless File.exist?(structs_path) && File.exist?(enums_path)
  abort "Missing generated files in #{docs_generated}. Run `scripts/generate_structs.rb` first."
end

structs = JSON.parse(File.read(structs_path))
enums = JSON.parse(File.read(enums_path))

def camel_to_snake(value)
  value
    .gsub(/([A-Z\d]+)([A-Z][a-z])/, '\\1_\\2')
    .gsub(/([a-z\d])([A-Z])/, '\\1_\\2')
    .downcase
end

log_field_enum = enums.fetch("LogStruct::LogField") do
  abort "LogStruct::LogField enum missing from #{enums_path}."
end

keys = log_field_enum.fetch("values", []).each_with_object({}) do |enum_value, memo|
  name = enum_value.fetch("name")
  serialized = enum_value.fetch("serialized")
  memo[camel_to_snake(name)] = serialized
end

keys = keys.sort.to_h

groups = Hash.new { |h, k| h[k] = {sources: [], events: []} }

def collect_serialized(field)
  unless field.is_a?(Hash)
    raise "Expected field metadata Hash but got #{field.inspect}"
  end

  values = []
  values << field["default_enum_serialized"]
  values << field["enum_value_serialized"]
  enum_values = field["enum_values_serialized"]
  values.concat(enum_values) if enum_values.is_a?(Array)

  values.compact.map(&:to_s).uniq
end

structs.each do |fq_name, info|
  next unless fq_name.start_with?("LogStruct::Log::")

  fields = info["fields"]
  unless fields.is_a?(Hash)
    raise "Struct #{fq_name} missing fields metadata"
  end

  event_field = fields["event"]
  next unless event_field

  event_values = collect_serialized(event_field)
  next if event_values.empty?

  log_type = fq_name.split("::")[2]
  unless log_type
    raise "Unable to infer log type for #{fq_name}"
  end

  group = groups[log_type]
  group[:events] = (group[:events] | event_values)

  source_field = fields["source"]
  if source_field
    source_values = collect_serialized(source_field)
    group[:sources] = (group[:sources] | source_values)
  end
end

catalog_structs = groups.each_with_object({}) do |(log_type, data), memo|
  events = data[:events].uniq.sort
  next if events.empty?

  sources = data[:sources].uniq
  fixed_source = (sources.size == 1) ? sources.first : nil

  memo[log_type] = {
    "name" => log_type,
    "fixed_source" => fixed_source,
    "allowed_events" => events
  }
end

catalog_structs = catalog_structs.sort.to_h

catalog = {"keys" => keys, "structs" => catalog_structs}

provider_dir = File.join(root, "terraform-provider-logstruct")
data_dir = File.join(provider_dir, "pkg", "data")
FileUtils.mkdir_p(data_dir)

catalog_path = File.join(data_dir, "catalog.json")
File.write(catalog_path, JSON.pretty_generate(catalog))

gen_path = File.join(data_dir, "catalog_gen.go")

def go_string(str)
  str.to_s.gsub("\\", "\\\\").gsub('"', '\\"')
end

go = +"// Code generated by scripts/export_provider_catalog.rb; DO NOT EDIT.\n"
go << "package data\n\n"
go << "func ptr[T any](v T) *T { return &v }\n\n"
go << "type StructCatalog struct {\n\tName string\n\tFixedSource *string\n\tAllowedEvents []string\n}\n\n"
go << "type Catalog struct {\n\tKeys map[string]string\n\tStructs map[string]StructCatalog\n}\n\n"
go << "var CatalogData = Catalog{\n\tKeys: map[string]string{\n"
keys.each do |key, value|
  go << "\t\t\"#{go_string(key)}\": \"#{go_string(value)}\",\n"
end
go << "\t},\n\tStructs: map[string]StructCatalog{\n"
catalog_structs.each do |name, data|
  go << "\t\t\"#{go_string(name)}\": {Name: \"#{go_string(data["name"])}\","
  fixed_source = data["fixed_source"]
  fragment = if fixed_source
    " FixedSource: ptr(\"#{go_string(fixed_source)}\"),"
  else
    " FixedSource: nil,"
  end
  go << fragment
  go << " AllowedEvents: []string{"
  events = data["allowed_events"]
  if events.any?
    go << events.map { |event| "\"#{go_string(event)}\"" }.join(", ")
  end
  go << "}},\n"
end
go << "\t},\n}\n"

File.write(gen_path, go)

puts "Wrote provider catalog to #{catalog_path} and #{gen_path}"

def check(condition, message)
  raise message unless condition
end

catalog_data = JSON.parse(File.read(catalog_path))
structs = catalog_data.fetch("structs")

check(structs.any?, "Struct catalog is empty")
check(structs.key?("GoodJob"), "Struct catalog missing GoodJob")
good_job = structs["GoodJob"]

check(good_job["allowed_events"].include?("enqueue"), "GoodJob missing enqueue event")
check(good_job["fixed_source"] == "job", "GoodJob fixed source incorrect")

go_contents = File.read(gen_path)

check(go_contents.include?("\"GoodJob\": {Name: \"GoodJob\""), "catalog_gen.go missing GoodJob entry")
check(go_contents.include?("AllowedEvents: []string{\"enqueue\""), "catalog_gen.go missing enqueue event")
