#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require "json"
require "fileutils"

root = File.expand_path("..", __dir__)
site_gen = File.join(root, "site", "lib", "log-generation")
enums_path = File.join(site_gen, "sorbet-enums.json")
structs_path = File.join(site_gen, "sorbet-log-structs.json")
keys_path = File.join(site_gen, "log-fields.json")

unless File.exist?(enums_path) && File.exist?(structs_path) && File.exist?(keys_path)
  abort "Missing generated files in #{site_gen}. Run scripts/all_check.sh first."
end

enums = JSON.parse(File.read(enums_path))
structs = JSON.parse(File.read(structs_path))
keys = JSON.parse(File.read(keys_path))

# Build lookup maps for enum serialized values
event_values = {}
(enums["LogStruct::Event"] || []).each { |e| event_values[e["name"]] = e["value"] }
source_values = {}
(enums["LogStruct::Source"] || []).each { |e| source_values[e["name"]] = e["value"] }

catalog = {"keys" => keys, "structs" => {}}

structs.each do |fq_name, info|
  name = info["name"] || fq_name.split("::").last
  fields = info["fields"] || {}
  s = {"name" => name}

  # Fixed source if enum_single
  if fields["source"] && fields["source"]["type"] == "enum_single" && fields["source"]["enum_value"]
    src_name = fields["source"]["enum_value"]
    s["fixed_source"] = source_values[src_name] || src_name.downcase
  else
    s["fixed_source"] = nil
  end

  # Allowed events (serialized)
  allowed = []
  if fields["event"]
    ef = fields["event"]
    case ef["type"]
    when "enum_single"
      if ef["enum_value"]
        nm = ef["enum_value"]
        allowed << (event_values[nm] || nm.downcase)
      end
    when "enum_union"
      (ef["enum_values"] || []).each do |nm|
        allowed << (event_values[nm] || nm.downcase)
      end
    end
  end
  s["allowed_events"] = allowed.uniq

  catalog["structs"][name] = s
end

provider_dir = File.join(root, "terraform-provider-logstruct")
data_dir = File.join(provider_dir, "pkg", "data")
FileUtils.mkdir_p(data_dir)

# Always write JSON (useful for inspection)
catalog_path = File.join(data_dir, "catalog.json")
File.write(catalog_path, JSON.pretty_generate(catalog))

# Also generate a Go source file with embedded types and data for zero runtime parsing
gen_path = File.join(data_dir, "catalog_gen.go")

def go_string(str)
  # Escape backslashes and quotes for Go string literals
  str.to_s.gsub("\\", "\\\\").gsub('"', '\\"')
end

go = +"// Code generated by scripts/export_provider_catalog.rb; DO NOT EDIT.\n"
go << "package data\n\n"
go << "func ptr[T any](v T) *T { return &v }\n\n"
go << "type StructCatalog struct {\n\tName string\n\tFixedSource *string\n\tAllowedEvents []string\n}\n\n"
go << "type Catalog struct {\n\tKeys map[string]string\n\tStructs map[string]StructCatalog\n}\n\n"
go << "var CatalogData = Catalog{\n\tKeys: map[string]string{\n"
keys.each do |k, v|
  go << "\t\t\"#{go_string(k)}\": \"#{go_string(v)}\",\n"
end
go << "\t},\n\tStructs: map[string]StructCatalog{\n"
catalog["structs"].each do |name, s|
  go << "\t\t\"#{go_string(name)}\": {Name: \"#{go_string(s["name"])}\","
  go << if s["fixed_source"]
    " FixedSource: ptr(\"#{go_string(s["fixed_source"])}\"),"
  else
    " FixedSource: nil,"
  end
  go << " AllowedEvents: []string{"
  go << s["allowed_events"].map { |ev| "\"#{go_string(ev)}\"" }.join(", ")
  go << "}},\n"
end
go << "\t},\n}\n"

File.write(gen_path, go)

puts "Wrote provider catalog to #{catalog_path} and #{gen_path}"
