# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class ActiveJob
      class Start < T::Struct
        extend T::Sig

        # Shared/common fields
        const :source, Source::Job, default: Source::Job
        const :event, Event, default: Event::Start
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        const :job_id, String
        const :job_class, String
        const :queue_name, T.nilable(Symbol), default: nil
        const :arguments, T.nilable(T::Array[T.untyped]), default: nil
        const :executions, T.nilable(Integer), default: nil
        const :provider_job_id, T.nilable(String), default: nil

        # Event-specific fields
        const :started_at, Time
        const :attempt, T.nilable(Integer), default: nil

        # Additional data

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          h = T.let({}, T::Hash[LogStruct::LogField, T.untyped])
          h[LogField::JobId] = job_id
          h[LogField::JobClass] = job_class
          h[LogField::QueueName] = queue_name unless queue_name.nil?
          h[LogField::Arguments] = arguments unless arguments.nil?
          h[LogField::Executions] = executions unless executions.nil?
          h[LogField::ProviderJobId] = provider_job_id unless provider_job_id.nil?
          h[LogField::StartedAt] = started_at
          h[LogField::Attempt] = attempt unless attempt.nil?
          h
        end
      end
    end
  end
end
