# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/serialize_common"
require "log_struct/shared/merge_additional_data_fields"
require "log_struct/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Shrine
      class Delete < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Shrine, default: Source::Shrine
        const :event, Event, default: Event::Delete
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        # Event-specific fields
        const :storage, Symbol
        const :location, String

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def self.base_hash
          {}
        end

        sig {
          params(storage: T.untyped,
            location: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(storage:,
          location:,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash
          h[LogField::Storage] = storage
          h[LogField::Location] = location
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            storage: storage,
            location: location,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
