# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_structs.rb
# Schemas dir: schemas/log_sources/
# Template: tools/codegen/templates/sorbet/event.rb.erb

require "log_struct/shared/interfaces/common_fields"
require "log_struct/shared/interfaces/additional_data_field"
require "log_struct/shared/interfaces/request_fields"
require "log_struct/shared/shared/serialize_common"
require "log_struct/shared/shared/merge_additional_data_fields"
require "log_struct/shared/shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Shrine
      class Upload < T::Struct
        # typed: strict
        # frozen_string_literal: true

        extend T::Sig

        extend T::Sig

        # Shared/common fields
        const :source, Source::Shrine, default: Source::Shrine
        const :event, Event, default: Event::Upload
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: Level::Info

        # Event-specific fields
        const :storage, String
        const :location, String
        const :upload_options, T.nilable(T::Hash[Symbol, T.untyped]), default: nil
        const :options, T.nilable(T::Hash[Symbol, T.untyped]), default: nil
        const :uploader, T.nilable(String), default: nil
        const :duration_ms, T.nilable(Float), default: nil

        # Additional data
        include LogStruct::Log::Interfaces::AdditionalDataField
        const :additional_data, T.nilable(T::Hash[T.any(String, Symbol), T.untyped]), default: nil
        include LogStruct::Log::Shared::MergeAdditionalDataFields

        # Request fields (optional)

        # Serialize shared fields
        include LogStruct::Log::Interfaces::CommonFields
        include LogStruct::Log::Shared::SerializeCommon

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def self.base_hash
          {}
        end

        sig {
          params(storage: T.untyped,
            location: T.untyped,
            upload_options: T.untyped,
            options: T.untyped,
            uploader: T.untyped,
            duration_ms: T.untyped,
            additional_data: T.untyped,
            timestamp: T.untyped).returns(T::Hash[LogStruct::LogField, T.untyped])
        }
        def self.build(storage:,
          location:,
          upload_options: nil,
          options: nil,
          uploader: nil,
          duration_ms: nil,
          additional_data: nil,
          timestamp: Time.now)
          h = base_hash
          h[LogField::Storage] = storage
          h[LogField::Location] = location
          h[LogField::UploadOptions] = upload_options unless upload_options.nil?
          h[LogField::Options] = options unless options.nil?
          h[LogField::Uploader] = uploader unless uploader.nil?
          h[LogField::DurationMs] = duration_ms unless duration_ms.nil?
          h
        end

        sig { returns(T::Hash[LogStruct::LogField, T.untyped]) }
        def to_h
          self.class.build(
            storage: storage,
            location: location,
            upload_options: upload_options,
            options: options,
            uploader: uploader,
            duration_ms: duration_ms,
            additional_data: additional_data,
            timestamp: timestamp
          )
        end
      end
    end
  end
end
