# typed: strict
# frozen_string_literal: true

# AUTO-GENERATED: DO NOT EDIT
# Generated by scripts/generate_log_structs.rb
# Schemas dir: schemas/log_sources/
# Template: scripts/templates/generate_log_structs/event.rb.erb

require_relative "../interfaces/common_fields"
require_relative "../interfaces/additional_data_field"
require_relative "../interfaces/request_fields"
require_relative "../shared/serialize_common"
require_relative "../shared/merge_additional_data_fields"
require_relative "../shared/add_request_fields"
require_relative "../../enums/source"
require_relative "../../enums/event"
require_relative "../../enums/level"
require_relative "../../enums/log_field"

module LogStruct
  module Log
    class Shrine
      class Upload < T::Struct
        extend T::Sig
        include Interfaces::CommonFields
        include SerializeCommon

        include Interfaces::AdditionalDataField
        include MergeAdditionalDataFields

        const :source, Source::Shrine, default: T.let(Source::Shrine, Source::Shrine)

        const :event, Event::Upload, default: T.let(Event::Upload, Event::Upload)
        const :timestamp, Time, factory: -> { Time.now }
        const :level, Level, default: T.let(Level::Info, Level)

        const :additional_data, T::Hash[Symbol, T.untyped], default: {}
        const :storage, String
        const :location, String
        const :upload_options, T.nilable(T::Hash[Symbol, T.untyped]), default: nil
        const :options, T.nilable(T::Hash[Symbol, T.untyped]), default: nil
        const :uploader, T.nilable(String), default: nil
        const :duration_ms, T.nilable(Float), default: nil

        sig { override.params(strict: T::Boolean).returns(T::Hash[Symbol, T.untyped]) }
        def serialize(strict = true)
          h = serialize_common(strict)
          merge_additional_data_fields(h)
          h[LogField::Storage.serialize] = storage
          h[LogField::Location.serialize] = location
          h[LogField::UploadOptions.serialize] = upload_options if upload_options
          h[LogField::Options.serialize] = options if options
          h[LogField::Uploader.serialize] = uploader if uploader
          h[LogField::DurationMs.serialize] = duration_ms if duration_ms
          h
        end
      end
    end
  end
end
